# Site settings
name: 想先生
location: 北京
#company: IBM
position: Java开发工程师
github: https://github.com/
facebook: https://www.facebook.com/
phone: XXX
email: array_xiangxiang@163.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

